version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo "Starting gradle build..."
      - chmod +x gradlew
      - ./gradlew clean build

artifacts:
  files:
    - build/libs/*.jar
